import type { Metadata } from "next";
import { Host_Grotesk, Inter } from "next/font/google";
import { Analytics } from '@vercel/analytics/next';
import { SmoothScroll } from "@/components/ui/smooth-scroll";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-family-inter",
});

const hostGrotesk = Host_Grotesk({
  subsets: ["latin"],
  variable: "--font-family-host",
});

export const metadata: Metadata = {
  title: "Aluminium",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${hostGrotesk.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col bg-background text-foreground">
        <SmoothScroll />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
